- id: 200
  key: satoshi
  code: btc
  symbol: "฿"
  coin: true
  quick_withdraw_max: 0
  rpc: http://djfioosidfiusdfiu:dkmfosdfu89dsu87sdfy78fsd7@127.0.0.1:18332
  blockchain: https://blockchain.info/tx/#{txid}
  address_url: https://blockchain.info/address/#{address}
  assets:
    accounts:
      -
        address: 1HjfnJpQmANtuW7yr1ggeDfyfe1kDK7rm3

- id: 400
  key: gravio
  code: gio
  symbol: "GIO"
  coin: true
  quick_withdraw_max: 0
  rpc: http://djfioosidfiusdfiu:dkmfosdfu89dsu87sdfy78fsd7@127.0.0.1:18333
  blockchain: https://blockchain.info/tx/#{txid}
  address_url: https://blockchain.info/address/#{address}
  assets:
    accounts:
      -
        address: GHjfnJpQmANtuW7yr1ggeDfyfe1kDK7rm3

