development: &defaults
  adapter: mysql2
  encoding: utf8
  database: peatio_development
  username: root
  password: b06fd0b2065f8b62c6b15647a3
  pool: 10
  reconnect: true

test:
  <<: *defaults
  database: peatio_test

production:
  <<: *defaults
  database: peatio_production
